version: "3.2"
services:
    data:
        image: shiroyuki/ghost:com.shiroyuki.v2018.data
        container_name: website.data
        hostname: datasvc
        # command: bash -c "echo $STATIC_DATA_PATH && ./mvnw spring-boot:run"
        command: tail -f /dev/null
        volumes:
            - type: bind
              source: ./data
              target: /opt/data
        ports:
            - 8080:8080
        environment:
            STATIC_DATA_PATH: /opt/data/static/pages/en
#
# volumes:
#     data:
#         driver: local
