version: "3.0"
services:
    data:
        image: shiroyuki/ghost:com.shiroyuki.v2018.data
        container_name: website.data
        hostname: datasvc
        command: ./mvnw spring-boot:run
        volumes:
            - data:/opt/data
        ports:
            - 8080:8080

volumes:
    data:
        driver: local
